version: '3'
services:
  python:
    restart: always
    build: .
    container_name: "docker-datascience-cpu"
    working_dir: /home/workspace
    tty: true
    volumes:
    - type: bind
      source: ../workspace
      target: /home/workspace